[project]
name = "minuteman"
version = "0.0.1"
authors = [
  {name = "Jared Magnusson", email = "jmag722@gmail.com"},
]
description = "Python library for solving engineering problems."
readme = "README.md"
requires-python = ">=3.10"
license = {file = "LICENSE"}
keywords = [
  "aerospace",
  "engineering",
  "minuteman",
  "physics",
  "science",
  "toolkit"
]
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Operating System :: OS Independent",
]
dependencies = [
  "numpy >= 2",
  "scipy",
]

[project.scripts]
fanno = "minuteman.cpg.cli_fanno:main"
isen = "minuteman.cpg.cli_isentropic:main"
nshock = "minuteman.cpg.cli_normal_shock:main"
oshock = "minuteman.cpg.cli_oblique_shock:main"
rayleigh= "minuteman.cpg.cli_rayleigh:main"

[dependency-groups]
dev = [
  "mkdocstrings",
  "mkdocstrings-python",
  "pyrefly",
  "pytest",
  "pytest-cov",
  "ruff",
  "zensical",
]

[tool.pytest.ini_options]
addopts = [
  "--import-mode=importlib",
]
pythonpath = [
  "src"
]

[tool.ruff]
line-length = 79
indent-width = 4

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
docstring-code-line-length = 79

[tool.ruff.lint]
select = ["ALL"]
fixable = ["ALL"]
ignore = [
    "ANN001", # missing type annotation for function
    "ANN202", # return types for private functions
    "ANN401", # using Any as a type
    "COM812", # trailing commas, `ruff format` already manages (avoid warning)
    "D", # docstring related errors
    "EM101", # raw string in exception
    "EM102", # f-string in exception
    "ERA001", # commented-out-code
    "PLR0913", # too-many-arguments
    "PLR0915", # too-many-statements
    "PLR0917", # too-many-positional-arguments
    "TRY003", # raise-vanilla-args
]
[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = [
    "ANN", # typing
    "D", # docstrings
    "INP001", # implicit-namespace-package
    "N803", # invalid-argument-name
    "N806", # non-lowercase-variable-in-function
    "S101", # flags use of assert
    "PLR", # magic values, too many args
]
"src/**/cli*.py" = [
    "T201",
]
[tool.ruff.lint.flake8-copyright]
author = "Jared Magnusson"
min-file-size = 1

[project.urls]
"Homepage" = "https://github.com/jmag722/minuteman"
"Bug Reports" = "https://github.com/jmag722/minuteman/issues"

[tool.pyrefly]
project-includes = [
    "src",
    "tests",
]
search_path = ["src", "."]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[tool.hatch.build.targets.wheel]
packages = ["src/minuteman"]
